name: datahouse CI/CD Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  # job 1: Build the image on GitHub-hosted machines and push to Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/production_api:latest


  # job 2: Deploy the image on a self-hosted runner
  deploy:
    runs-on: [self-hosted, noIP]
    needs: build-and-push
    steps:
      - name: Pull and Restart App Container 
        run: |
          # 1. Stop the existing container if it is running
          docker stop production_api || true
          docker rm production_api || true

          # 2. Pull the latest image from Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/production_api:latest

          # 3. Create a temporary .env file from Github Secrets
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

          # 4. Run the updated container with the new image and inject the file
          docker run -d --name production_api -p 80:80 --restart unless-stopped --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/production_api:latest

          # 5. Securely remove the temporary .env file after use
          rm -f .env
    
          # 6. Clean up dangling images to free up space
          docker image prune -f

    
  